"use client";

import { useEffect, useRef, useState } from "react";
import { StorySegment, StoryChoice, StoryConfig } from "../types";

interface StoryPlayerProps {
  segments: StorySegment[];
  isLoading: boolean;
  isComplete: boolean;
  turnCount: number;
  config: StoryConfig | null;
  onChoice: (choice: StoryChoice) => void;
  onCustomInput: (text: string) => void;
  onExport: () => string;
  onReset: () => void;
}

function TypingIndicator() {
  return (
    <div className="flex items-center gap-3 p-6">
      <div className="flex items-center gap-1.5">
        <div className="w-2 h-2 bg-amber-400 rounded-full animate-bounce" />
        <div className="w-2 h-2 bg-amber-400 rounded-full animate-bounce delay-150" />
        <div className="w-2 h-2 bg-amber-400 rounded-full animate-bounce delay-300" />
      </div>
      <span className="text-amber-400/60 text-sm italic">The story unfolds...</span>
    </div>
  );
}

export default function StoryPlayer({
  segments,
  isLoading,
  isComplete,
  turnCount,
  config,
  onChoice,
  onCustomInput,
  onExport,
  onReset,
}: StoryPlayerProps) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const [customInput, setCustomInput] = useState("");
  const [showCustomInput, setShowCustomInput] = useState(false);
  const [copiedExport, setCopiedExport] = useState(false);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTo({
        top: scrollRef.current.scrollHeight,
        behavior: "smooth",
      });
    }
  }, [segments, isLoading]);

  const latestAISegment = [...segments].reverse().find((s) => s.narrator === "ai");

  const handleCustomSubmit = () => {
    if (customInput.trim()) {
      onCustomInput(customInput.trim());
      setCustomInput("");
      setShowCustomInput(false);
    }
  };

  const handleExport = () => {
    const text = onExport();
    navigator.clipboard.writeText(text).then(() => {
      setCopiedExport(true);
      setTimeout(() => setCopiedExport(false), 2000);
    });
  };

  const handleDownload = async () => {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxW = pageW - margin * 2;
    let y = 20;

    const addPage = () => { doc.addPage(); y = 20; };
    const checkY = (need: number) => { if (y + need > 270) addPage(); };

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(50, 50, 50);
    doc.text(`${config?.theme || "Story"} Adventure`, pageW / 2, y, { align: "center" });
    y += 10;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(13);
    doc.setTextColor(120, 120, 120);
    doc.text(config?.subgenre || "", pageW / 2, y, { align: "center" });
    y += 8;

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageW - margin, y);
    y += 6;

    // Meta
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Setting: ${config?.setting || ""}`, margin, y);
    y += 5;
    doc.text(`Tone: ${config?.tone || ""}`, margin, y);
    y += 7;

    // Characters
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(50, 50, 50);
    doc.text("Characters", margin, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    config?.characters.forEach((c) => {
      checkY(6);
      doc.text(`  ${c.name} (${c.role}): ${c.personality}`, margin, y);
      y += 5;
    });
    y += 4;
    doc.line(margin, y, pageW - margin, y);
    y += 8;

    // Story segments
    segments.forEach((seg) => {
      if (seg.narrator === "ai") {
        doc.setFont("times", "normal");
        doc.setFontSize(11);
        doc.setTextColor(40, 40, 40);
      } else {
        doc.setFont("helvetica", "italic");
        doc.setFontSize(10);
        doc.setTextColor(140, 110, 30);
      }
      const prefix = seg.narrator === "user" ? "Your choice: " : "";
      const lines = doc.splitTextToSize(`${prefix}${seg.text}`, maxW);
      lines.forEach((line: string) => {
        checkY(6);
        doc.text(line, margin, y);
        y += 5;
      });
      y += 4;
    });

    // Footer
    checkY(14);
    y += 2;
    doc.line(margin, y, pageW - margin, y);
    y += 6;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(160, 160, 160);
    doc.text("Generated by Story Weaver — Interactive AI Storytelling Adventure", pageW / 2, y, { align: "center" });

    doc.save(`${config?.theme || "story"}-adventure.pdf`);
  };

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <header className="border-b border-gray-800/50 bg-gray-950/80 backdrop-blur-sm sticky top-0 z-20">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="text-xl">📖</span>
            <div>
              <h1 className="text-sm font-bold text-amber-300">Story Weaver</h1>
              <p className="text-xs text-gray-500">
                {config?.theme} — {config?.subgenre} · Chapter {turnCount}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleExport}
              className="px-3 py-1.5 text-xs text-gray-400 hover:text-amber-300 border border-gray-700/50 rounded-lg hover:border-amber-600/30 transition-colors"
              title="Copy story to clipboard"
            >
              {copiedExport ? "✓ Copied!" : "📋 Copy"}
            </button>
            <button
              onClick={handleDownload}
              className="px-3 py-1.5 text-xs text-gray-400 hover:text-amber-300 border border-gray-700/50 rounded-lg hover:border-amber-600/30 transition-colors"
              title="Download story as PDF"
            >
              💾 PDF
            </button>
            <button
              onClick={onReset}
              className="px-3 py-1.5 text-xs text-gray-400 hover:text-red-400 border border-gray-700/50 rounded-lg hover:border-red-600/30 transition-colors"
            >
              New Story
            </button>
          </div>
        </div>
      </header>

      {/* Story Content */}
      <div ref={scrollRef} className="flex-1 overflow-y-auto px-4 py-8">
        <div className="max-w-3xl mx-auto space-y-6">
          {segments.map((segment) => (
            <div
              key={segment.id}
              className={`animate-fadeIn ${
                segment.narrator === "ai" ? "" : "flex justify-end"
              }`}
            >
              {segment.narrator === "ai" ? (
                <div className="prose prose-invert prose-amber max-w-none">
                  <div className="text-gray-200 leading-relaxed whitespace-pre-line text-[15px] font-serif">
                    {segment.text}
                  </div>
                </div>
              ) : (
                <div className="inline-block max-w-md">
                  <div className="bg-amber-600/20 border border-amber-600/30 rounded-2xl rounded-br-sm px-5 py-3">
                    <p className="text-amber-200 text-sm italic">
                      ✦ {segment.text}
                    </p>
                  </div>
                </div>
              )}
            </div>
          ))}

          {isLoading && <TypingIndicator />}

          {/* Story Complete */}
          {isComplete && (
            <div className="text-center py-8 animate-fadeIn">
              <div className="text-5xl mb-4">🏁</div>
              <h2 className="text-2xl font-bold text-amber-200 mb-2">
                The End
              </h2>
              <p className="text-gray-400 mb-6">
                Your adventure has reached its conclusion. What a journey!
              </p>
              <div className="flex items-center justify-center gap-3">
                <button
                  onClick={handleDownload}
                  className="px-6 py-3 bg-amber-600 hover:bg-amber-500 text-gray-950 font-semibold rounded-xl transition-colors"
                >
                  💾 Download Story
                </button>
                <button
                  onClick={handleExport}
                  className="px-6 py-3 border border-amber-600/50 text-amber-300 hover:bg-amber-600/10 rounded-xl transition-colors"
                >
                  {copiedExport ? "✓ Copied!" : "📋 Copy to Clipboard"}
                </button>
                <button
                  onClick={onReset}
                  className="px-6 py-3 border border-gray-700 text-gray-400 hover:text-gray-200 hover:border-gray-500 rounded-xl transition-colors"
                >
                  🔄 New Adventure
                </button>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Choices / Input Area */}
      {!isComplete && !isLoading && latestAISegment?.choices && (
        <div className="border-t border-gray-800/50 bg-gray-950/90 backdrop-blur-sm">
          <div className="max-w-3xl mx-auto px-4 py-5">
            <p className="text-xs text-gray-500 uppercase tracking-wider mb-3">
              What do you do?
            </p>
            <div className="space-y-2">
              {latestAISegment.choices.map((choice) => (
                <button
                  key={choice.id}
                  onClick={() => onChoice(choice)}
                  className="w-full text-left p-4 bg-gray-900/50 border border-gray-700/50 rounded-xl hover:border-amber-500/50 hover:bg-amber-500/5 transition-all duration-200 group"
                >
                  <span className="text-amber-500 font-bold mr-2 text-sm group-hover:text-amber-400">
                    {choice.id.toUpperCase()}.
                  </span>
                  <span className="text-gray-300 group-hover:text-gray-100 text-sm">
                    {choice.text}
                  </span>
                </button>
              ))}
            </div>

            {/* Custom input toggle */}
            <div className="mt-4">
              {showCustomInput ? (
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={customInput}
                    onChange={(e) => setCustomInput(e.target.value)}
                    onKeyDown={(e) => e.key === "Enter" && handleCustomSubmit()}
                    placeholder="Describe your own action..."
                    className="flex-1 p-3 bg-gray-900/50 border border-gray-700/50 rounded-xl text-gray-200 placeholder:text-gray-600 focus:outline-none focus:border-amber-500/50 text-sm"
                    autoFocus
                  />
                  <button
                    onClick={handleCustomSubmit}
                    disabled={!customInput.trim()}
                    className="px-5 py-3 bg-amber-600 hover:bg-amber-500 disabled:bg-gray-800 disabled:text-gray-600 text-gray-950 font-semibold rounded-xl transition-colors text-sm"
                  >
                    Go
                  </button>
                  <button
                    onClick={() => setShowCustomInput(false)}
                    className="px-3 py-3 text-gray-500 hover:text-gray-300 transition-colors text-sm"
                  >
                    ✕
                  </button>
                </div>
              ) : (
                <button
                  onClick={() => setShowCustomInput(true)}
                  className="text-xs text-gray-600 hover:text-amber-400 transition-colors"
                >
                  ✏️ Or write your own action...
                </button>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
